### PR TITLE
SLING-12144 - Bump non-sling dependencies to latest in org.apache.sling.testing.sling-mock

### PR DESCRIPTION
**Pull request by rmcdouga**
Bump dependencies:

Mockito: 4.7.0 -> 5.7.0
commons-lang 2.6 -> commons-lang3 3.13.0
commons-io 2.11.0 -> 2.13.0
commons-collectios4 4.2 -> 4.4
JUnit5 5.2.0 -> 5.10.1

### CODE REVIEW

**Comment by stefanseifert** [comment]
thanks for this PR! some comments:

* updating the testing dependencies junit and and mockito is an non-brainer and should be done immediately
  * however, we should keep those testing deps in all the mocks and we should update it also in osgi-mock, jcr-mock, resourceresolver-mock - but this is separate form this PR
* it's also a good thing that we can finally get rid of commons-lang 2 (it was still there because former dependencies required it, but it's no longer the case)

* for updating the other dependencies it's always a balancing act: sling-mock is used in a lot of projects, and most of them do not have the luxury to always use the latest dependencies from everything. in fact, it's used a lot in downstream products as AEM and i try to keep compatibility for the versions still in use. in those cases, the dependencies that are actually used in the test run are not determined by the POM here, but but the dependencies defined in the project and target environment, e.g. using the ways described here: https://wcm.io/testing/aem-mock/usage-maven-dependencies.html
* so in sling-mock, i usually keep the dependencies older and only update in a bunch every 1-2 years with a focus on maximum compatibility (last time in [SLING-11295](https://issues.apache.org/jira/browse/SLING-11295)).
* if we update those 3rparty deps (or sling deps) too early, we risk that new features are used in the code of sling-mock itself, and that breaks the tests if used in older environment's projects

best thing would be to split up this PR in one only affecting the testing dependencies, probably one for removing commons-lang 2. i'm not sure if there is  benefit in updating the other 3rdparty dependencies currently (commons-lang3 is used in version 3.9 as inherited form osgi-mock). i also keep those 3dparty deps in sync across all mocks.

**Comment by rmcdouga** [comment]
OK, I will split up the changes into multiple PRs as requested.

I'm not sure I agree with the idea of using older dependency versions for compatibility with older downstream product versions.  Older versions of sling-mock are still available for projects targeting these older product versions.  I'm used to (and am comfortable with) projects like Spring that move to the latest versions of dependencies pretty aggressively.  It encourages the whole ecosystem to continuously upgrade their dependencies.   Upgrading dependencies is like exercise - the more frequently you do it, the easier it gets.  

Having said that, the dependencies we're talking about are only a couple of point releases old, so that's pretty current.  I don't feel too bad about leaving them alone.  

I will split into a PR for testing dependencies in this project, one for commons-lang (but to version 3.9), and will have a look at the other projects you mention and I'll raise PRs in those projects for the testing dependencies.  

If that plan is acceptable, then feel free to close this PR.

One more thing - How would you like to handle the JIRA issues?  Should I raise separate issues for each PR or can I continue to use the same JIRA issue for all PRs?

**Comment by stefanseifert** [comment]
> I'm not sure I agree with the idea of using older dependency versions for compatibility with older downstream product versions. Older versions of [sling-mock](https://issues.apache.org/jira/browse/SLING-mock) are still available for projects targeting these older product versions. I'm used to (and am comfortable with) projects like Spring that move to the latest versions of dependencies pretty aggressively. It encourages the whole ecosystem to continuously upgrade their dependencies. Upgrading dependencies is like exercise - the more frequently you do it, the easier it gets.

in general i'm completely on your side, but if you are e.g. stuck in an older AEM 6.5 project, you are bound to work with a  certain set of outdated 3rdparty dependencies - but still may want to use the latest features provided by sling-mock.

> One more thing - How would you like to handle the JIRA issues? Should I raise separate issues for each PR or can I continue to use the same JIRA issue for all PRs?

normally we prefer separate JIRA issues for separate topics and PRs, but in this case it's fine to link them to the already existing ticket as they are all related to dependency updates.

**Comment by rmcdouga** [comment]
> in general i'm completely on your side, but if you are e.g. stuck in an older AEM 6.5 project, you are bound to work with a certain set of outdated 3rdparty dependencies - but still may want to use the latest features provided by [sling-mock](https://issues.apache.org/jira/browse/SLING-mock).

Ironically, I had the opposite problem.  I'm using the latest version of AEM and I am using the latest aem-mock but was stuck with the old dependencies (thanks to old dependencies in sling-testing-hamcrest).  You can't please everyone. 😃 

Since you can't please everyone, personally, I would aim to please the people who stay current.  This makes their life easier and it puts additional pressure on the laggards to upgrade more regularly if they want the latest features (which is the "right thing to do", so while they may not like it, it's in their best interest and if they do it more regularly it will become easier).

> normally we prefer separate JIRA issues for separate topics and PRs, but in this case it's fine to link them to the already existing ticket as they are all related to dependency updates.

OK, will do.  Thanks for reviewing this and for the detailed comments.

**Comment by stefanseifert** [comment]
superseded by #32 and 333

**Pull request closed without merging**
